from __future__ import annotations

"""Read-only probability layer for the Streamlit preview.

The S-state engine remains the source of truth.  This module only maps the
current engine output to the historical probability JSON generated by the
separate HistoricalTraining repository.
"""

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

MODEL_PATH = Path(__file__).resolve().parent / "models" / "probability_model.json"
DISPLAY_HORIZONS = (6, 12, 18)  # 24H / 48H / 72H
PRIMARY_HORIZON = 18            # 3 days for swing-capital efficiency
MAX_PREVIEW_LEVEL = 5           # live monitor now exports HistoricalTraining-compatible state_age_bars


def _bin_bandpos(value: float) -> str:
    if value < 0.25:
        return "LT_025"
    if value < 0.50:
        return "025_050"
    if value < 0.60:
        return "050_060"
    if value < 0.75:
        return "060_075"
    return "GE_075"


def _bandwidth_trend(record: dict[str, Any]) -> tuple[str, float]:
    """Use the exact historical-training definition whenever live arrays exist."""
    upper = list(record.get("_bb_upper_series") or [])
    lower = list(record.get("_bb_lower_series") or [])
    mid = list(record.get("_bb_basis_series") or [])

    # Also support snapshot_ai.json records for offline verification.
    if len(upper) < 4 or len(lower) < 4 or len(mid) < 4:
        chart = list(record.get("chart_30d") or [])
        if len(chart) >= 4:
            tail = chart[-4:]
            upper = [x.get("bb_upper") for x in tail]
            lower = [x.get("bb_lower") for x in tail]
            mid = [x.get("bb_midline") for x in tail]

    if len(upper) < 4 or len(lower) < 4 or len(mid) < 4:
        return "UNKNOWN", 0.0

    widths: list[float] = []
    try:
        for u, l, m in zip(upper[-4:], lower[-4:], mid[-4:]):
            mf = float(m)
            widths.append(((float(u) - float(l)) / abs(mf) * 100.0) if abs(mf) > 1e-18 else 0.0)
    except (TypeError, ValueError):
        return "UNKNOWN", 0.0

    delta = widths[-1] - widths[0]
    if delta > 0.20:
        return "EXPANDING", delta
    if delta < -0.20:
        return "CONTRACTING", delta
    return "FLAT", delta


@lru_cache(maxsize=2)
def load_probability_model(path: str | None = None) -> dict[str, Any]:
    model_path = Path(path) if path else MODEL_PATH
    if not model_path.exists():
        return {
            "available": False,
            "reason": "model_file_missing",
            "model_path": str(model_path),
        }
    try:
        payload = json.loads(model_path.read_text(encoding="utf-8"))
    except Exception as exc:  # UI must not break if model JSON is damaged.
        return {
            "available": False,
            "reason": f"model_load_error:{type(exc).__name__}",
            "model_path": str(model_path),
        }
    payload["available"] = True
    payload["model_path"] = str(model_path)
    return payload


def extract_live_features(record: dict[str, Any], opportunity: dict[str, Any]) -> dict[str, Any]:
    current = opportunity.get("current") or {}
    midline = opportunity.get("midline") or {}
    try:
        bandpos = float(current.get("ha_band_position", 0.5) or 0.5)
    except (TypeError, ValueError):
        bandpos = 0.5
    bandwidth_state, bandwidth_delta = _bandwidth_trend(record)
    state_age_bars = record.get("_state_age_bars")
    state_age_bin = record.get("_state_age_bin")
    if state_age_bars is None:
        state_age_bars = record.get("state_age_bars")
    if not state_age_bin:
        state_age_bin = record.get("state_age_bin")

    return {
        "midline_state": str(midline.get("state") or "unknown"),
        "bandpos": bandpos,
        "bandpos_bin": _bin_bandpos(bandpos),
        "trigger_stage": str(opportunity.get("trigger_stage") or "T0"),
        "bandwidth_trend": bandwidth_state,
        "bandwidth_delta_3d": round(float(bandwidth_delta), 8),
        "state_age_bars": int(state_age_bars) if state_age_bars is not None else None,
        "state_age_bin": str(state_age_bin) if state_age_bin else None,
    }


def _signature(features: dict[str, Any], fields: list[str]) -> str:
    if not fields:
        return "BASELINE"
    return "|".join(f"{field}={features.get(field)}" for field in fields)


def _outcome_payload(node: dict[str, Any]) -> dict[str, Any]:
    """Normalize v2 four-way settlement fields while staying v1-compatible."""
    outcomes = node.get("outcomes") or {}

    def p(key: str) -> float | None:
        item = outcomes.get(key) or {}
        value = item.get("probability")
        try:
            return float(value) if value is not None else None
        except (TypeError, ValueError):
            return None

    success = p("SUCCESS_WITHIN_HORIZON")
    alive = p("ALIVE_SLOW")
    true_fail = p("TRUE_FAIL")
    other = p("OTHER")

    if success is None:
        try:
            success = float(node.get("probability", 0.0))
        except (TypeError, ValueError):
            success = 0.0

    try:
        survival = node.get("structural_survival_probability")
        survival = float(survival) if survival is not None else None
    except (TypeError, ValueError):
        survival = None

    if survival is None and alive is not None:
        survival = success + alive

    return {
        "outcomes": outcomes,
        "success_probability": success,
        "alive_slow_probability": alive,
        "true_fail_probability": true_fail,
        "other_probability": other,
        "structural_survival_probability": survival,
        "late_success_4_7d": node.get("late_success_4_7d"),
    }


def lookup_probability(
    model: dict[str, Any],
    *,
    state: str,
    horizon: int,
    features: dict[str, Any],
    max_level: int = MAX_PREVIEW_LEVEL,
) -> dict[str, Any]:
    if not model.get("available", True):
        return {"available": False, "reason": model.get("reason", "model_unavailable")}

    state_node = (model.get("states") or {}).get(state)
    if not state_node:
        return {"available": False, "reason": "state_missing"}
    hnode = (state_node.get("horizons") or {}).get(str(horizon))
    if not hnode:
        return {"available": False, "reason": "horizon_missing"}

    min_samples = int(model.get("default_min_samples", 50))
    levels = [x for x in (hnode.get("levels") or []) if int(x.get("level", 0)) <= int(max_level)]
    for level in reversed(levels):
        fields = list(level.get("fields") or [])
        sig = _signature(features, fields)
        for rule in level.get("rules") or []:
            if rule.get("signature") == sig and int(rule.get("samples", 0)) >= min_samples:
                return {
                    "available": True,
                    "probability": float(rule["probability"]),
                    "raw_probability": float(rule.get("raw_probability", rule["probability"])),
                    "samples": int(rule["samples"]),
                    "wins": int(rule["wins"]),
                    "level": int(level.get("level", 0)),
                    "fields": fields,
                    "signature": sig,
                    "wilson95": rule.get("wilson95"),
                    "fallback": False,
                    **_outcome_payload(rule),
                }

    base = hnode.get("baseline") or {}
    if not base:
        return {"available": False, "reason": "baseline_missing"}
    return {
        "available": True,
        "probability": float(base.get("probability", 0.0)),
        "raw_probability": float(base.get("raw_probability", base.get("probability", 0.0))),
        "samples": int(base.get("samples", 0)),
        "wins": int(base.get("wins", 0)),
        "level": 0,
        "fields": [],
        "signature": "BASELINE",
        "wilson95": base.get("wilson95"),
        "fallback": True,
        **_outcome_payload(base),
    }


def predict_record(
    record: dict[str, Any],
    opportunity: dict[str, Any] | None = None,
    horizons: tuple[int, ...] = DISPLAY_HORIZONS,
) -> dict[str, Any]:
    opp = opportunity or record.get("_long_opportunity") or record.get("opportunity_long") or {}
    state = str(opp.get("market_state_id") or "OTHER")
    if state not in {"S0.5", "S1", "S2", "S3"}:
        return {"available": False, "reason": "state_not_modeled", "state": state}

    model = load_probability_model()
    if not model.get("available"):
        return {"available": False, "reason": model.get("reason", "model_unavailable"), "state": state}

    features = extract_live_features(record, opp)
    predictions: dict[str, Any] = {}
    for horizon in horizons:
        predictions[str(horizon)] = lookup_probability(
            model,
            state=state,
            horizon=int(horizon),
            features=features,
            max_level=MAX_PREVIEW_LEVEL,
        )

    primary = predictions.get(str(PRIMARY_HORIZON)) or {}
    target = ((model.get("states") or {}).get(state) or {}).get("target")
    return {
        "available": bool(primary.get("available")),
        "state": state,
        "target": target,
        "features": features,
        "predictions": predictions,
        "primary_horizon": PRIMARY_HORIZON,
        "primary": primary,
        "model_id": model.get("model_id"),
        "generated_at": model.get("generated_at"),
        "max_level": MAX_PREVIEW_LEVEL,
    }




def human_feature_summary(features: dict[str, Any]) -> str:
    mid_map = {
        'rising': '中軌上斜',
        'flat': '中軌平緩',
        'flattening': '中軌走平',
        'falling': '中軌下斜',
        'unknown': '中軌未知',
    }
    band_map = {
        'LT_025': '位置<0.25',
        '025_050': '位置0.25-0.50',
        '050_060': '位置0.50-0.60',
        '060_075': '位置0.60-0.75',
        'GE_075': '位置>0.75',
    }
    trig_map = {
        'T0': 'T0等待轉黃',
        'T1': 'T1剛觸發',
        'T2': 'T2已觸發',
    }
    bw_map = {
        'EXPANDING': '布林擴張',
        'CONTRACTING': '布林收縮',
        'FLAT': '布林平穩',
        'UNKNOWN': '布林未知',
    }
    parts = [
        mid_map.get(str(features.get('midline_state') or 'unknown'), f"中軌{features.get('midline_state') or '未知'}"),
        band_map.get(str(features.get('bandpos_bin') or ''), f"位置{features.get('bandpos_bin') or '?'}"),
        trig_map.get(str(features.get('trigger_stage') or 'T0'), f"觸發{features.get('trigger_stage') or 'T0'}"),
        bw_map.get(str(features.get('bandwidth_trend') or 'UNKNOWN'), f"布林{features.get('bandwidth_trend') or '未知'}"),
    ]
    age_bin = str(features.get('state_age_bin') or '')
    age_map = {'1':'狀態第1根4H','2_3':'狀態2-3根4H','4_6':'狀態4-6根4H','7_PLUS':'狀態7+根4H'}
    if age_bin:
        parts.append(age_map.get(age_bin, f'狀態年齡{age_bin}'))
    return '｜'.join(parts)

def state_target_label(state: str) -> str:
    return {
        "S0.5": "3日內轉強",
        "S1": "3日內上攻",
        "S2": "3日內轉S3",
        "S3": "3日內續強",
    }.get(state, "3日機率")
