"""SState US-stock / ETF / commodity identity dictionary.

Canonical human-maintained identity map for the Pionex RWA symbols used by
SStateMarketTerminal news research.  Each entry pins the real ticker, exchange,
qualified market ticker, English/Traditional-Chinese name, asset type and aliases.
"""

US_STOCK_ALIASES = {
    "AAOIX": {
        "ticker": "AAOI",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:AAOI",
        "name_en": "Applied Optoelectronics, Inc.",
        "name_zh": "應用光電",
        "asset_type": "company",
        "aliases": ["Applied Optoelectronics", "應用光電", "NASDAQ:AAOI"],
    },
    "AAPLX": {
        "ticker": "AAPL",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:AAPL",
        "name_en": "Apple Inc.",
        "name_zh": "蘋果",
        "asset_type": "company",
        "aliases": ["Apple", "蘋果公司", "NASDAQ:AAPL"],
    },
    "AAX": {
        "ticker": "AA",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:AA",
        "name_en": "Alcoa Corporation",
        "name_zh": "美國鋁業",
        "asset_type": "company",
        "aliases": ["Alcoa", "美國鋁業", "NYSE:AA"],
    },
    "AMATX": {
        "ticker": "AMAT",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:AMAT",
        "name_en": "Applied Materials, Inc.",
        "name_zh": "應用材料",
        "asset_type": "company",
        "aliases": ["Applied Materials", "應用材料", "NASDAQ:AMAT"],
    },
    "AMDX": {
        "ticker": "AMD",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:AMD",
        "name_en": "Advanced Micro Devices, Inc.",
        "name_zh": "超微半導體",
        "asset_type": "company",
        "aliases": ["AMD", "Advanced Micro Devices", "超微", "超微半導體", "NASDAQ:AMD"],
    },
    "AMZNX": {
        "ticker": "AMZN",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:AMZN",
        "name_en": "Amazon.com, Inc.",
        "name_zh": "亞馬遜",
        "asset_type": "company",
        "aliases": ["Amazon", "Amazon.com", "亞馬遜", "NASDAQ:AMZN"],
    },
    "ANTHROPIC": {
        "ticker": "ANTHROPIC",
        "exchange": "PRIVATE",
        "qualified_ticker": "PRIVATE:ANTHROPIC",
        "name_en": "Anthropic PBC",
        "name_zh": "Anthropic（Claude 開發商）",
        "asset_type": "private_company",
        "aliases": ["Anthropic", "Claude", "Anthropic PBC"],
    },
    "APPX": {
        "ticker": "APP",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:APP",
        "name_en": "AppLovin Corporation",
        "name_zh": "AppLovin",
        "asset_type": "company",
        "aliases": ["AppLovin", "NASDAQ:APP"],
    },
    "ARMX": {
        "ticker": "ARM",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:ARM",
        "name_en": "Arm Holdings plc",
        "name_zh": "安謀控股",
        "asset_type": "company",
        "aliases": ["Arm", "Arm Holdings", "安謀", "NASDAQ:ARM"],
    },
    "ASMLX": {
        "ticker": "ASML",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:ASML",
        "name_en": "ASML Holding N.V.",
        "name_zh": "艾司摩爾",
        "asset_type": "company",
        "aliases": ["ASML", "ASML Holding", "艾司摩爾", "NASDAQ:ASML"],
    },
    "ASTSX": {
        "ticker": "ASTS",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:ASTS",
        "name_en": "AST SpaceMobile, Inc.",
        "name_zh": "AST SpaceMobile",
        "asset_type": "company",
        "aliases": ["AST SpaceMobile", "NASDAQ:ASTS"],
    },
    "AVGOX": {
        "ticker": "AVGO",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:AVGO",
        "name_en": "Broadcom Inc.",
        "name_zh": "博通",
        "asset_type": "company",
        "aliases": ["Broadcom", "博通", "NASDAQ:AVGO"],
    },
    "AXTIX": {
        "ticker": "AXTI",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:AXTI",
        "name_en": "AXT, Inc.",
        "name_zh": "AXT",
        "asset_type": "company",
        "aliases": ["AXT Inc", "NASDAQ:AXTI"],
    },
    "BEX": {
        "ticker": "BE",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:BE",
        "name_en": "Bloom Energy Corporation",
        "name_zh": "Bloom Energy",
        "asset_type": "company",
        "aliases": ["Bloom Energy", "NYSE:BE"],
    },
    "BMNRX": {
        "ticker": "BMNR",
        "exchange": "NYSEAMERICAN",
        "qualified_ticker": "NYSEAMERICAN:BMNR",
        "name_en": "BitMine Immersion Technologies, Inc.",
        "name_zh": "BitMine Immersion Technologies",
        "asset_type": "company",
        "aliases": ["BitMine", "BitMine Immersion Technologies", "BMNR"],
    },
    "BNOX": {
        "ticker": "BNO",
        "exchange": "NYSEARCA",
        "qualified_ticker": "NYSEARCA:BNO",
        "name_en": "United States Brent Oil Fund, LP",
        "name_zh": "美國布蘭特原油基金",
        "asset_type": "etf",
        "aliases": ["United States Brent Oil Fund", "Brent Oil ETF", "布蘭特原油 ETF", "NYSEARCA:BNO"],
    },
    "BRENTOIL": {
        "ticker": "BRENT",
        "exchange": "COMMODITY",
        "qualified_ticker": "COMMODITY:BRENT",
        "name_en": "Brent Crude Oil",
        "name_zh": "布蘭特原油",
        "asset_type": "commodity",
        "aliases": ["Brent crude", "Brent oil", "布蘭特原油"],
    },
    "CBRS": {
        "ticker": "CBRS",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:CBRS",
        "name_en": "Cerebras Systems, Inc.",
        "name_zh": "Cerebras Systems",
        "asset_type": "company",
        "aliases": ["Cerebras", "Cerebras Systems", "NASDAQ:CBRS"],
    },
    "CEGX": {
        "ticker": "CEG",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:CEG",
        "name_en": "Constellation Energy Corporation",
        "name_zh": "Constellation Energy／星座能源",
        "asset_type": "company",
        "aliases": ["Constellation Energy", "星座能源", "NASDAQ:CEG"],
    },
    "CF": {
        "ticker": "CF",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:CF",
        "name_en": "CF Industries Holdings, Inc.",
        "name_zh": "CF Industries",
        "asset_type": "company",
        "aliases": ["CF Industries", "NYSE:CF"],
    },
    "CIFRX": {
        "ticker": "CIFR",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:CIFR",
        "name_en": "Cipher Mining Inc.",
        "name_zh": "Cipher Mining",
        "asset_type": "company",
        "aliases": ["Cipher Mining", "NASDAQ:CIFR"],
    },
    "WTI": {
        "ticker": "WTI",
        "exchange": "COMMODITY",
        "qualified_ticker": "COMMODITY:WTI",
        "name_en": "West Texas Intermediate Crude Oil",
        "name_zh": "西德州中質原油",
        "asset_type": "commodity",
        "aliases": ["WTI crude oil", "West Texas Intermediate", "西德州原油"],
    },
    "COHRX": {
        "ticker": "COHR",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:COHR",
        "name_en": "Coherent Corp.",
        "name_zh": "Coherent／高意",
        "asset_type": "company",
        "aliases": ["Coherent Corp", "Coherent", "高意", "NYSE:COHR"],
    },
    "COINX": {
        "ticker": "COIN",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:COIN",
        "name_en": "Coinbase Global, Inc.",
        "name_zh": "Coinbase",
        "asset_type": "company",
        "aliases": ["Coinbase", "Coinbase Global", "NASDAQ:COIN"],
    },
    "COPPER": {
        "ticker": "COPPER",
        "exchange": "COMMODITY",
        "qualified_ticker": "COMMODITY:COPPER",
        "name_en": "Copper",
        "name_zh": "銅",
        "asset_type": "commodity",
        "aliases": ["Copper futures", "COMEX copper", "銅"],
    },
    "CPERX": {
        "ticker": "CPER",
        "exchange": "NYSEARCA",
        "qualified_ticker": "NYSEARCA:CPER",
        "name_en": "United States Copper Index Fund",
        "name_zh": "美國銅指數基金",
        "asset_type": "etf",
        "aliases": ["United States Copper Index Fund", "Copper ETF", "銅 ETF", "NYSEARCA:CPER"],
    },
    "CRCLX": {
        "ticker": "CRCL",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:CRCL",
        "name_en": "Circle Internet Group, Inc.",
        "name_zh": "Circle",
        "asset_type": "company",
        "aliases": ["Circle", "Circle Internet Group", "NYSE:CRCL"],
    },
    "CRDOX": {
        "ticker": "CRDO",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:CRDO",
        "name_en": "Credo Technology Group Holding Ltd",
        "name_zh": "Credo Technology",
        "asset_type": "company",
        "aliases": ["Credo", "Credo Technology", "NASDAQ:CRDO"],
    },
    "CRWVX": {
        "ticker": "CRWV",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:CRWV",
        "name_en": "CoreWeave, Inc.",
        "name_zh": "CoreWeave",
        "asset_type": "company",
        "aliases": ["CoreWeave", "NASDAQ:CRWV"],
    },
    "CSCOX": {
        "ticker": "CSCO",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:CSCO",
        "name_en": "Cisco Systems, Inc.",
        "name_zh": "思科",
        "asset_type": "company",
        "aliases": ["Cisco", "Cisco Systems", "思科", "NASDAQ:CSCO"],
    },
    "CVXX": {
        "ticker": "CVX",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:CVX",
        "name_en": "Chevron Corporation",
        "name_zh": "雪佛龍",
        "asset_type": "company",
        "aliases": ["Chevron", "雪佛龍", "NYSE:CVX"],
    },
    "DELLX": {
        "ticker": "DELL",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:DELL",
        "name_en": "Dell Technologies Inc.",
        "name_zh": "戴爾科技",
        "asset_type": "company",
        "aliases": ["Dell", "Dell Technologies", "戴爾", "NYSE:DELL"],
    },
    "DRAMX": {
        "ticker": "DRAM",
        "exchange": "CBOE",
        "qualified_ticker": "CBOE:DRAM",
        "name_en": "Roundhill Memory ETF",
        "name_zh": "Roundhill 記憶體 ETF",
        "asset_type": "etf",
        "aliases": ["Roundhill Memory ETF", "Memory ETF", "記憶體 ETF", "CBOE:DRAM"],
    },
    "EWJX": {
        "ticker": "EWJ",
        "exchange": "NYSEARCA",
        "qualified_ticker": "NYSEARCA:EWJ",
        "name_en": "iShares MSCI Japan ETF",
        "name_zh": "iShares MSCI 日本 ETF",
        "asset_type": "etf",
        "aliases": ["iShares MSCI Japan ETF", "日本 ETF", "NYSEARCA:EWJ"],
    },
    "EWYX": {
        "ticker": "EWY",
        "exchange": "NYSEARCA",
        "qualified_ticker": "NYSEARCA:EWY",
        "name_en": "iShares MSCI South Korea ETF",
        "name_zh": "iShares MSCI 韓國 ETF",
        "asset_type": "etf",
        "aliases": ["iShares MSCI South Korea ETF", "韓國 ETF", "NYSEARCA:EWY"],
    },
    "FLNCX": {
        "ticker": "FLNC",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:FLNC",
        "name_en": "Fluence Energy, Inc.",
        "name_zh": "Fluence Energy",
        "asset_type": "company",
        "aliases": ["Fluence Energy", "NASDAQ:FLNC"],
    },
    "GEVX": {
        "ticker": "GEV",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:GEV",
        "name_en": "GE Vernova Inc.",
        "name_zh": "GE Vernova",
        "asset_type": "company",
        "aliases": ["GE Vernova", "NYSE:GEV"],
    },
    "GLWX": {
        "ticker": "GLW",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:GLW",
        "name_en": "Corning Incorporated",
        "name_zh": "康寧",
        "asset_type": "company",
        "aliases": ["Corning", "康寧", "NYSE:GLW"],
    },
    "GMEX": {
        "ticker": "GME",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:GME",
        "name_en": "GameStop Corp.",
        "name_zh": "GameStop",
        "asset_type": "company",
        "aliases": ["GameStop", "NYSE:GME"],
    },
    "GOOGLX": {
        "ticker": "GOOGL",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:GOOGL",
        "name_en": "Alphabet Inc.",
        "name_zh": "Alphabet／Google",
        "asset_type": "company",
        "aliases": ["Alphabet", "Google", "谷歌", "NASDAQ:GOOGL"],
    },
    "GSGX": {
        "ticker": "GSG",
        "exchange": "NYSEARCA",
        "qualified_ticker": "NYSEARCA:GSG",
        "name_en": "iShares S&P GSCI Commodity-Indexed Trust",
        "name_zh": "iShares S&P GSCI 商品指數信託",
        "asset_type": "etf",
        "aliases": ["GSG", "commodity ETF", "商品 ETF", "NYSEARCA:GSG"],
    },
    "HIMSX": {
        "ticker": "HIMS",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:HIMS",
        "name_en": "Hims & Hers Health, Inc.",
        "name_zh": "Hims & Hers Health",
        "asset_type": "company",
        "aliases": ["Hims & Hers", "Hims", "NYSE:HIMS"],
    },
    "HOODX": {
        "ticker": "HOOD",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:HOOD",
        "name_en": "Robinhood Markets, Inc.",
        "name_zh": "Robinhood",
        "asset_type": "company",
        "aliases": ["Robinhood", "NASDAQ:HOOD"],
    },
    "HPEX": {
        "ticker": "HPE",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:HPE",
        "name_en": "Hewlett Packard Enterprise Company",
        "name_zh": "慧與科技",
        "asset_type": "company",
        "aliases": ["Hewlett Packard Enterprise", "HPE", "慧與", "NYSE:HPE"],
    },
    "HYUNDAI": {
        "ticker": "005380",
        "exchange": "KRX",
        "qualified_ticker": "KRX:005380",
        "name_en": "Hyundai Motor Company",
        "name_zh": "現代汽車",
        "asset_type": "foreign_company",
        "aliases": ["Hyundai Motor", "Hyundai", "現代汽車", "KRX:005380"],
    },
    "IBMX": {
        "ticker": "IBM",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:IBM",
        "name_en": "International Business Machines Corporation",
        "name_zh": "IBM／國際商業機器",
        "asset_type": "company",
        "aliases": ["IBM", "International Business Machines", "NYSE:IBM"],
    },
    "INTCX": {
        "ticker": "INTC",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:INTC",
        "name_en": "Intel Corporation",
        "name_zh": "英特爾",
        "asset_type": "company",
        "aliases": ["Intel", "英特爾", "NASDAQ:INTC"],
    },
    "IRENX": {
        "ticker": "IREN",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:IREN",
        "name_en": "IREN Limited",
        "name_zh": "IREN",
        "asset_type": "company",
        "aliases": ["IREN", "IREN Limited", "NASDAQ:IREN"],
    },
    "LITEX": {
        "ticker": "LITE",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:LITE",
        "name_en": "Lumentum Holdings Inc.",
        "name_zh": "Lumentum",
        "asset_type": "company",
        "aliases": ["Lumentum", "NASDAQ:LITE"],
    },
    "LLYX": {
        "ticker": "LLY",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:LLY",
        "name_en": "Eli Lilly and Company",
        "name_zh": "禮來",
        "asset_type": "company",
        "aliases": ["Eli Lilly", "Lilly", "禮來", "NYSE:LLY"],
    },
    "LMTX": {
        "ticker": "LMT",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:LMT",
        "name_en": "Lockheed Martin Corporation",
        "name_zh": "洛克希德馬丁",
        "asset_type": "company",
        "aliases": ["Lockheed Martin", "洛克希德馬丁", "NYSE:LMT"],
    },
    "LNGX": {
        "ticker": "LNG",
        "exchange": "NYSEAMERICAN",
        "qualified_ticker": "NYSEAMERICAN:LNG",
        "name_en": "Cheniere Energy, Inc.",
        "name_zh": "Cheniere Energy",
        "asset_type": "company",
        "aliases": ["Cheniere Energy", "LNG", "NYSEAMERICAN:LNG"],
    },
    "LRCXX": {
        "ticker": "LRCX",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:LRCX",
        "name_en": "Lam Research Corporation",
        "name_zh": "科林研發",
        "asset_type": "company",
        "aliases": ["Lam Research", "科林研發", "NASDAQ:LRCX"],
    },
    "METAX": {
        "ticker": "META",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:META",
        "name_en": "Meta Platforms, Inc.",
        "name_zh": "Meta",
        "asset_type": "company",
        "aliases": ["Meta", "Meta Platforms", "Facebook", "NASDAQ:META"],
    },
    "MOSX": {
        "ticker": "MOS",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:MOS",
        "name_en": "The Mosaic Company",
        "name_zh": "美盛",
        "asset_type": "company",
        "aliases": ["Mosaic", "The Mosaic Company", "美盛", "NYSE:MOS"],
    },
    "MPX": {
        "ticker": "MP",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:MP",
        "name_en": "MP Materials Corp.",
        "name_zh": "MP Materials",
        "asset_type": "company",
        "aliases": ["MP Materials", "NYSE:MP"],
    },
    "MRVLX": {
        "ticker": "MRVL",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:MRVL",
        "name_en": "Marvell Technology, Inc.",
        "name_zh": "Marvell／邁威爾科技",
        "asset_type": "company",
        "aliases": ["Marvell", "邁威爾科技", "NASDAQ:MRVL"],
    },
    "MSFTX": {
        "ticker": "MSFT",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:MSFT",
        "name_en": "Microsoft Corporation",
        "name_zh": "微軟",
        "asset_type": "company",
        "aliases": ["Microsoft", "微軟", "NASDAQ:MSFT"],
    },
    "MSTRX": {
        "ticker": "MSTR",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:MSTR",
        "name_en": "Strategy Inc.",
        "name_zh": "Strategy（原 MicroStrategy）",
        "asset_type": "company",
        "aliases": ["Strategy", "MicroStrategy", "微策略", "NASDAQ:MSTR"],
    },
    "MUX": {
        "ticker": "MU",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:MU",
        "name_en": "Micron Technology, Inc.",
        "name_zh": "美光科技",
        "asset_type": "company",
        "aliases": ["Micron", "Micron Technology", "美光", "NASDAQ:MU"],
    },
    "NATGAS": {
        "ticker": "NATGAS",
        "exchange": "COMMODITY",
        "qualified_ticker": "COMMODITY:NATGAS",
        "name_en": "Natural Gas",
        "name_zh": "天然氣",
        "asset_type": "commodity",
        "aliases": ["Natural gas", "Henry Hub natural gas", "天然氣"],
    },
    "NBISX": {
        "ticker": "NBIS",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:NBIS",
        "name_en": "Nebius Group N.V.",
        "name_zh": "Nebius Group",
        "asset_type": "company",
        "aliases": ["Nebius", "Nebius Group", "NASDAQ:NBIS"],
    },
    "NFLXX": {
        "ticker": "NFLX",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:NFLX",
        "name_en": "Netflix, Inc.",
        "name_zh": "Netflix／網飛",
        "asset_type": "company",
        "aliases": ["Netflix", "網飛", "NASDAQ:NFLX"],
    },
    "NKEX": {
        "ticker": "NKE",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:NKE",
        "name_en": "NIKE, Inc.",
        "name_zh": "Nike／耐吉",
        "asset_type": "company",
        "aliases": ["Nike", "耐吉", "NYSE:NKE"],
    },
    "NOKX": {
        "ticker": "NOK",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:NOK",
        "name_en": "Nokia Corporation",
        "name_zh": "諾基亞",
        "asset_type": "company",
        "aliases": ["Nokia", "諾基亞", "NYSE:NOK"],
    },
    "NOWX": {
        "ticker": "NOW",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:NOW",
        "name_en": "ServiceNow, Inc.",
        "name_zh": "ServiceNow",
        "asset_type": "company",
        "aliases": ["ServiceNow", "NYSE:NOW"],
    },
    "NTRX": {
        "ticker": "NTR",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:NTR",
        "name_en": "Nutrien Ltd.",
        "name_zh": "Nutrien",
        "asset_type": "company",
        "aliases": ["Nutrien", "NYSE:NTR"],
    },
    "NVDAX": {
        "ticker": "NVDA",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:NVDA",
        "name_en": "NVIDIA Corporation",
        "name_zh": "輝達",
        "asset_type": "company",
        "aliases": ["NVIDIA", "Nvidia", "輝達", "NASDAQ:NVDA"],
    },
    "OKLOX": {
        "ticker": "OKLO",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:OKLO",
        "name_en": "Oklo Inc.",
        "name_zh": "Oklo",
        "asset_type": "company",
        "aliases": ["Oklo", "NYSE:OKLO"],
    },
    "ONDSX": {
        "ticker": "ONDS",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:ONDS",
        "name_en": "Ondas Holdings Inc.",
        "name_zh": "Ondas Holdings",
        "asset_type": "company",
        "aliases": ["Ondas", "Ondas Holdings", "NASDAQ:ONDS"],
    },
    "OPENAI": {
        "ticker": "OPENAI",
        "exchange": "PRIVATE",
        "qualified_ticker": "PRIVATE:OPENAI",
        "name_en": "OpenAI",
        "name_zh": "OpenAI",
        "asset_type": "private_company",
        "aliases": ["OpenAI", "ChatGPT"],
    },
    "ORCLX": {
        "ticker": "ORCL",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:ORCL",
        "name_en": "Oracle Corporation",
        "name_zh": "甲骨文",
        "asset_type": "company",
        "aliases": ["Oracle", "甲骨文", "NYSE:ORCL"],
    },
    "PAYPX": {
        "ticker": "PAYP",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:PAYP",
        "name_en": "PayPay Corporation",
        "name_zh": "PayPay（行動支付）",
        "asset_type": "foreign_company",
        "aliases": ["PayPay", "PayPay Corporation", "NASDAQ:PAYP"],
    },
    "PLTRX": {
        "ticker": "PLTR",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:PLTR",
        "name_en": "Palantir Technologies Inc.",
        "name_zh": "Palantir",
        "asset_type": "company",
        "aliases": ["Palantir", "NASDAQ:PLTR"],
    },
    "QCOMX": {
        "ticker": "QCOM",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:QCOM",
        "name_en": "QUALCOMM Incorporated",
        "name_zh": "高通",
        "asset_type": "company",
        "aliases": ["Qualcomm", "高通", "NASDAQ:QCOM"],
    },
    "QNTX": {
        "ticker": "QNT",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:QNT",
        "name_en": "Quantinuum Inc.",
        "name_zh": "Quantinuum",
        "asset_type": "company",
        "aliases": ["Quantinuum", "量子運算 Quantinuum", "NASDAQ:QNT"],
    },
    "QQQX": {
        "ticker": "QQQ",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:QQQ",
        "name_en": "Invesco QQQ Trust",
        "name_zh": "Invesco QQQ ETF",
        "asset_type": "etf",
        "aliases": ["Invesco QQQ", "QQQ ETF", "NASDAQ:QQQ"],
    },
    "RGTIX": {
        "ticker": "RGTI",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:RGTI",
        "name_en": "Rigetti Computing, Inc.",
        "name_zh": "Rigetti Computing",
        "asset_type": "company",
        "aliases": ["Rigetti", "Rigetti Computing", "NASDAQ:RGTI"],
    },
    "RKLBX": {
        "ticker": "RKLB",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:RKLB",
        "name_en": "Rocket Lab Corporation",
        "name_zh": "Rocket Lab",
        "asset_type": "company",
        "aliases": ["Rocket Lab", "NASDAQ:RKLB"],
    },
    "RTXX": {
        "ticker": "RTX",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:RTX",
        "name_en": "RTX Corporation",
        "name_zh": "RTX／雷神技術",
        "asset_type": "company",
        "aliases": ["RTX", "Raytheon Technologies", "雷神技術", "NYSE:RTX"],
    },
    "SITMX": {
        "ticker": "SITM",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:SITM",
        "name_en": "SiTime Corporation",
        "name_zh": "SiTime",
        "asset_type": "company",
        "aliases": ["SiTime", "NASDAQ:SITM"],
    },
    "SKHX": {
        "ticker": "000660",
        "exchange": "KRX",
        "qualified_ticker": "KRX:000660",
        "name_en": "SK hynix Inc.",
        "name_zh": "SK 海力士",
        "asset_type": "foreign_company",
        "aliases": ["SK hynix", "SK Hynix", "SK 海力士", "海力士", "KRX:000660"],
    },
    "SLVX": {
        "ticker": "SLV",
        "exchange": "NYSEARCA",
        "qualified_ticker": "NYSEARCA:SLV",
        "name_en": "iShares Silver Trust",
        "name_zh": "iShares 白銀信託",
        "asset_type": "etf",
        "aliases": ["iShares Silver Trust", "Silver ETF", "白銀 ETF", "NYSEARCA:SLV"],
    },
    "SMHX": {
        "ticker": "SMH",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:SMH",
        "name_en": "VanEck Semiconductor ETF",
        "name_zh": "VanEck 半導體 ETF",
        "asset_type": "etf",
        "aliases": ["VanEck Semiconductor ETF", "Semiconductor ETF", "半導體 ETF", "NASDAQ:SMH"],
    },
    "SMSN": {
        "ticker": "SMSN",
        "exchange": "LSE",
        "qualified_ticker": "LSE:SMSN",
        "name_en": "Samsung Electronics Co., Ltd. GDR",
        "name_zh": "三星電子",
        "asset_type": "foreign_company",
        "aliases": ["Samsung Electronics", "Samsung", "三星電子", "LSE:SMSN", "KRX:005930"],
    },
    "SNDKX": {
        "ticker": "SNDK",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:SNDK",
        "name_en": "Sandisk Corporation",
        "name_zh": "SanDisk／閃迪",
        "asset_type": "company",
        "aliases": ["Sandisk", "SanDisk", "閃迪", "NASDAQ:SNDK"],
    },
    "SOXLX": {
        "ticker": "SOXL",
        "exchange": "NYSEARCA",
        "qualified_ticker": "NYSEARCA:SOXL",
        "name_en": "Direxion Daily Semiconductor Bull 3X Shares",
        "name_zh": "Direxion 半導體三倍做多 ETF",
        "asset_type": "etf",
        "aliases": ["SOXL", "Semiconductor Bull 3X", "半導體三倍做多", "NYSEARCA:SOXL"],
    },
    "SOXXX": {
        "ticker": "SOXX",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:SOXX",
        "name_en": "iShares Semiconductor ETF",
        "name_zh": "iShares 半導體 ETF",
        "asset_type": "etf",
        "aliases": ["iShares Semiconductor ETF", "SOXX", "半導體 ETF", "NASDAQ:SOXX"],
    },
    "SPCX": {
        "ticker": "SPCX",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:SPCX",
        "name_en": "SpaceX",
        "name_zh": "SpaceX／太空探索科技",
        "asset_type": "company",
        "aliases": ["SpaceX", "Space Exploration Technologies", "太空探索科技", "NASDAQ:SPCX"],
    },
    "SPYX": {
        "ticker": "SPY",
        "exchange": "NYSEARCA",
        "qualified_ticker": "NYSEARCA:SPY",
        "name_en": "SPDR S&P 500 ETF Trust",
        "name_zh": "SPDR S&P 500 ETF",
        "asset_type": "etf",
        "aliases": ["SPDR S&P 500 ETF Trust", "S&P 500 ETF", "標普500 ETF", "NYSEARCA:SPY"],
    },
    "STXX": {
        "ticker": "STX",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:STX",
        "name_en": "Seagate Technology Holdings plc",
        "name_zh": "希捷科技",
        "asset_type": "company",
        "aliases": ["Seagate", "Seagate Technology", "希捷科技", "NASDAQ:STX"],
    },
    "TQQQX": {
        "ticker": "TQQQ",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:TQQQ",
        "name_en": "ProShares UltraPro QQQ",
        "name_zh": "ProShares 三倍做多納指 ETF",
        "asset_type": "etf",
        "aliases": ["TQQQ", "UltraPro QQQ", "三倍做多納指", "NASDAQ:TQQQ"],
    },
    "TSLAX": {
        "ticker": "TSLA",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:TSLA",
        "name_en": "Tesla, Inc.",
        "name_zh": "特斯拉",
        "asset_type": "company",
        "aliases": ["Tesla", "特斯拉", "NASDAQ:TSLA"],
    },
    "TSMX": {
        "ticker": "TSM",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:TSM",
        "name_en": "Taiwan Semiconductor Manufacturing Company Limited ADR",
        "name_zh": "台積電 ADR",
        "asset_type": "company",
        "aliases": ["TSMC", "Taiwan Semiconductor", "台積電", "NYSE:TSM"],
    },
    "TTEX": {
        "ticker": "TTE",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:TTE",
        "name_en": "TotalEnergies SE ADR",
        "name_zh": "道達爾能源 ADR",
        "asset_type": "company",
        "aliases": ["TotalEnergies", "道達爾能源", "NYSE:TTE"],
    },
    "TXNX": {
        "ticker": "TXN",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:TXN",
        "name_en": "Texas Instruments Incorporated",
        "name_zh": "德州儀器",
        "asset_type": "company",
        "aliases": ["Texas Instruments", "德州儀器", "NASDAQ:TXN"],
    },
    "UNGX": {
        "ticker": "UNG",
        "exchange": "NYSEARCA",
        "qualified_ticker": "NYSEARCA:UNG",
        "name_en": "United States Natural Gas Fund, LP",
        "name_zh": "美國天然氣基金",
        "asset_type": "etf",
        "aliases": ["United States Natural Gas Fund", "Natural Gas ETF", "天然氣 ETF", "NYSEARCA:UNG"],
    },
    "UNHX": {
        "ticker": "UNH",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:UNH",
        "name_en": "UnitedHealth Group Incorporated",
        "name_zh": "聯合健康",
        "asset_type": "company",
        "aliases": ["UnitedHealth", "UnitedHealth Group", "聯合健康", "NYSE:UNH"],
    },
    "URAX": {
        "ticker": "URA",
        "exchange": "NYSEARCA",
        "qualified_ticker": "NYSEARCA:URA",
        "name_en": "Global X Uranium ETF",
        "name_zh": "Global X 鈾礦 ETF",
        "asset_type": "etf",
        "aliases": ["Global X Uranium ETF", "Uranium ETF", "鈾礦 ETF", "NYSEARCA:URA"],
    },
    "URNMX": {
        "ticker": "URNM",
        "exchange": "NYSEARCA",
        "qualified_ticker": "NYSEARCA:URNM",
        "name_en": "Sprott Uranium Miners ETF",
        "name_zh": "Sprott 鈾礦商 ETF",
        "asset_type": "etf",
        "aliases": ["Sprott Uranium Miners ETF", "Uranium Miners ETF", "鈾礦商 ETF", "NYSEARCA:URNM"],
    },
    "USARX": {
        "ticker": "USAR",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:USAR",
        "name_en": "USA Rare Earth, Inc.",
        "name_zh": "USA Rare Earth／美國稀土",
        "asset_type": "company",
        "aliases": ["USA Rare Earth", "美國稀土", "NASDAQ:USAR"],
    },
    "USOX": {
        "ticker": "USO",
        "exchange": "NYSEARCA",
        "qualified_ticker": "NYSEARCA:USO",
        "name_en": "United States Oil Fund, LP",
        "name_zh": "美國原油基金",
        "asset_type": "etf",
        "aliases": ["United States Oil Fund", "US Oil ETF", "原油 ETF", "NYSEARCA:USO"],
    },
    "VGKX": {
        "ticker": "VGK",
        "exchange": "NYSEARCA",
        "qualified_ticker": "NYSEARCA:VGK",
        "name_en": "Vanguard FTSE Europe ETF",
        "name_zh": "Vanguard 歐洲 ETF",
        "asset_type": "etf",
        "aliases": ["Vanguard FTSE Europe ETF", "Europe ETF", "歐洲 ETF", "NYSEARCA:VGK"],
    },
    "WDCX": {
        "ticker": "WDC",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:WDC",
        "name_en": "Western Digital Corporation",
        "name_zh": "威騰電子",
        "asset_type": "company",
        "aliases": ["Western Digital", "WD", "威騰", "NASDAQ:WDC"],
    },
    "XAG": {
        "ticker": "XAG",
        "exchange": "COMMODITY",
        "qualified_ticker": "COMMODITY:XAG",
        "name_en": "Silver",
        "name_zh": "白銀",
        "asset_type": "commodity",
        "aliases": ["Silver", "spot silver", "白銀"],
    },
    "XAU": {
        "ticker": "XAU",
        "exchange": "COMMODITY",
        "qualified_ticker": "COMMODITY:XAU",
        "name_en": "Gold",
        "name_zh": "黃金",
        "asset_type": "commodity",
        "aliases": ["Gold", "spot gold", "黃金"],
    },
    "XPD": {
        "ticker": "XPD",
        "exchange": "COMMODITY",
        "qualified_ticker": "COMMODITY:XPD",
        "name_en": "Palladium",
        "name_zh": "鈀金",
        "asset_type": "commodity",
        "aliases": ["Palladium", "鈀金"],
    },
    "XPT": {
        "ticker": "XPT",
        "exchange": "COMMODITY",
        "qualified_ticker": "COMMODITY:XPT",
        "name_en": "Platinum",
        "name_zh": "鉑金",
        "asset_type": "commodity",
        "aliases": ["Platinum", "鉑金"],
    },
    "XYZX": {
        "ticker": "XYZ",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:XYZ",
        "name_en": "Block, Inc.",
        "name_zh": "Block（原 Square）",
        "asset_type": "company",
        "aliases": ["Block Inc", "Square", "Cash App", "Block", "NYSE:XYZ"],
    },
    "ALABX": {
        "ticker": "ALAB",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:ALAB",
        "name_en": "Astera Labs, Inc.",
        "name_zh": "Astera Labs",
        "asset_type": "company",
        "aliases": ["Astera Labs", "NASDAQ:ALAB"],
    },
    "KLACX": {
        "ticker": "KLAC",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:KLAC",
        "name_en": "KLA Corporation",
        "name_zh": "科磊",
        "asset_type": "company",
        "aliases": ["KLA", "KLA Corporation", "科磊", "NASDAQ:KLAC"],
    },
    "ONX": {
        "ticker": "ON",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:ON",
        "name_en": "onsemi",
        "name_zh": "安森美半導體",
        "asset_type": "company",
        "aliases": ["onsemi", "ON Semiconductor", "安森美", "安森美半導體", "NASDAQ:ON"],
    },
    "SKHY": {
        "ticker": "SKHY",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:SKHY",
        "name_en": "SK hynix Inc. ADR",
        "name_zh": "SK 海力士 ADR",
        "asset_type": "foreign_company",
        "aliases": ["SK hynix", "SK Hynix", "SK 海力士", "海力士", "NASDAQ:SKHY", "KRX:000660"],
    },
    "SMCIX": {
        "ticker": "SMCI",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:SMCI",
        "name_en": "Super Micro Computer, Inc.",
        "name_zh": "美超微電腦",
        "asset_type": "company",
        "aliases": ["Super Micro Computer", "Supermicro", "美超微", "NASDAQ:SMCI"],
    },
    "SNXXX": {
        "ticker": "SNX",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:SNX",
        "name_en": "TD SYNNEX Corporation",
        "name_zh": "TD SYNNEX",
        "asset_type": "company",
        "aliases": ["TD SYNNEX", "Synnex", "NYSE:SNX"],
    },
    "VSHX": {
        "ticker": "VSH",
        "exchange": "NYSE",
        "qualified_ticker": "NYSE:VSH",
        "name_en": "Vishay Intertechnology, Inc.",
        "name_zh": "Vishay／威世科技",
        "asset_type": "company",
        "aliases": ["Vishay", "Vishay Intertechnology", "威世", "NYSE:VSH"],
    },
    "KIOXIA": {
        "ticker": "285A",
        "exchange": "TSE",
        "qualified_ticker": "TSE:285A",
        "name_en": "Kioxia Holdings Corporation",
        "name_zh": "鎧俠控股",
        "asset_type": "foreign_company",
        "aliases": ["Kioxia", "Kioxia Holdings", "鎧俠", "TSE:285A"],
    },
    "PANWX": {
        "ticker": "PANW",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:PANW",
        "name_en": "Palo Alto Networks, Inc.",
        "name_zh": "Palo Alto Networks",
        "asset_type": "company",
        "aliases": ["Palo Alto Networks", "PANW", "NASDAQ:PANW"],
    },
    "SHAZX": {
        "ticker": "SHAZ",
        "exchange": "NASDAQ",
        "qualified_ticker": "NASDAQ:SHAZ",
        "name_en": "SharonAI Holdings Inc.",
        "name_zh": "SharonAI Holdings",
        "asset_type": "company",
        "aliases": ["SharonAI", "Sharon AI", "NASDAQ:SHAZ"],
    },
    "SOXSX": {
        "ticker": "SOXS",
        "exchange": "NYSEARCA",
        "qualified_ticker": "NYSEARCA:SOXS",
        "name_en": "Direxion Daily Semiconductor Bear 3X Shares",
        "name_zh": "Direxion 半導體三倍做空 ETF",
        "asset_type": "etf",
        "aliases": ["SOXS", "Semiconductor Bear 3X", "半導體三倍做空", "NYSEARCA:SOXS"],
    },
    "XLPX": {
        "ticker": "XLP",
        "exchange": "NYSEARCA",
        "qualified_ticker": "NYSEARCA:XLP",
        "name_en": "Consumer Staples Select Sector SPDR Fund",
        "name_zh": "SPDR 必需消費類股 ETF",
        "asset_type": "etf",
        "aliases": ["XLP", "Consumer Staples Select Sector SPDR", "必需消費 ETF", "NYSEARCA:XLP"],
    },
    "XLVX": {
        "ticker": "XLV",
        "exchange": "NYSEARCA",
        "qualified_ticker": "NYSEARCA:XLV",
        "name_en": "Health Care Select Sector SPDR Fund",
        "name_zh": "SPDR 醫療保健類股 ETF",
        "asset_type": "etf",
        "aliases": ["XLV", "Health Care Select Sector SPDR", "醫療保健 ETF", "NYSEARCA:XLV"],
    },
}

def get_stock_identity(symbol: str) -> dict | None:
    return US_STOCK_ALIASES.get(str(symbol).upper().strip())
